# URL apuntando a la base de datos que acabamos de crear
spring.datasource.url=jdbc:mysql://localhost:3306/bumeran?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# Tu usuario de MySQL (por defecto suele ser root)
spring.datasource.username=root
# Tu CONTRASEÑA real de acceso a MySQL (la que pusiste al instalar MySQL)
spring.datasource.password=toor

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ver los errores de SQL en la consola
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG