spring.datasource.url=jdbc:mysql://mysql:3306/bumeran?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.thymeleaf.prefix=file:/app/frontend-thymeleaf/templates/
spring.web.resources.static-locations=file:/app/frontend-thymeleaf/static/
spring.thymeleaf.cache=false
